### PR TITLE
ng - updated UI, titles, keys voting, toasts, minted modal fix

### PR DESCRIPTION
**Pull request by nikitattt**
This PR introduces a collection of updates, additions and bug fixes. 

Updates:
- Navigation bar. It’s brought into a similar look to nouns.wtf navBar.
- App uses `PT ROOT UI` instead of system font for sans-serif.
- When the vote button is disabled, the cursor is set to ‘Not-Allowed’.
- Reworked app main titles:
	- Titles during the ongoing auction were updated with better colours and texts.
	- During gameplay, titles dynamically provide information on how many votes are required to reach a consensus. Or, if consensus is not reachable anymore, state this.
- Removed vote time left in the form of text-based numbers.
- Removed consensus progress bar.
- Time left for voting is now shown in the form of the progress bar.

Additions:
- Toasts when new bids appear in the last 5 min of the auction and when someone submits tx to settle the auction during Fomo.
- Voting with keyboard left-right arrow keys.
- Disabled vertical scroll with arrow keys.

Bug fixes:
- Fixed error with “we minted noun” modal showing incorrect noun due to a race condition. Fixed it’s not central vertical positioning on desktop.

### CODE REVIEW

**Comment by lastpunk9999** [comment]
Hi @nikitattt,
There is some fantastic work in this PR, with tangible benefit to FOMO players. There is also some work which I think requires iteration. Unfortunately, given the size of this request (the number of features it combines and the sheer number of files it touches), it's not feasible to properly evaluate the changes it introduces.

I defer to @theforager on this, but I will not be able to take a look at the code changes in their current form. My suggestion is to submit focused PR that incrementally change the codebase, thus allowing proper testing, review, feedback, and iteration.

Thank you for making FOMO better! Many of these new features will make their way to prod, they just require another avenue to do so 🙇

**Comment by nikitattt** [comment]
Hi @lastpunk9999,

Thank you for the comment!

As work has started in the more classical app development model `dev branch -> live beta testing -> merge into main` in decision with @theforager to ensure proper development speed, and as a big amount of work has been done in this PR, and as it touched a big part of the application and involved fine-tuning during life testing, breaking all updates into distinct feature PR will require significant development time to ensure they all lead to the same end state behaviour.

Changes proposed in this PR have been live tested for 3 weeks without any major functionality issue reported, and all other minor fixes were introduced after they had been reported. It can be concluded that this PR is safe to merge and won’t lead to Fomo gameplay failure. With this, I propose merging this PR per the initially scoped plan. But of course, looking forward to hearing @theforager decision.

As to moving forward with future updates and given that you will now be available for peer review, I’m looking forward to future cooperation on introducing incremental updates to Fomo!

**Comment by theforager** [comment]
Hey @nikitattt, I sent you a note on this, but I agree with @lastpunk9999 that we should try and split this up.

There’s various things we’ll want to look into or clean-up, a few bugs, etc. This will be way easier to work through if we can break it into pieces, and it’ll derisk any issues with FOMO itself as we can launch with small changes to see if it breaks.

Thanks for all the hard work you’ve put into this and appreciate all your effort. I know this is extra work for you, but I think it’ll be in the long term best interests to keep FOMO well managed and get your enhancements out!

**Comment by nikitattt** [comment]
Great! Let me close this PR then and move into breaking updates into distinct PR. Looking forward to your technical feedback!

**Pull request closed without merging**
